/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ComposeGetDefaultCommandRequest = {
  composeId: string;
};

/** @internal */
export const ComposeGetDefaultCommandRequest$inboundSchema: z.ZodType<
  ComposeGetDefaultCommandRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  composeId: z.string(),
});

/** @internal */
export type ComposeGetDefaultCommandRequest$Outbound = {
  composeId: string;
};

/** @internal */
export const ComposeGetDefaultCommandRequest$outboundSchema: z.ZodType<
  ComposeGetDefaultCommandRequest$Outbound,
  z.ZodTypeDef,
  ComposeGetDefaultCommandRequest
> = z.object({
  composeId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComposeGetDefaultCommandRequest$ {
  /** @deprecated use `ComposeGetDefaultCommandRequest$inboundSchema` instead. */
  export const inboundSchema = ComposeGetDefaultCommandRequest$inboundSchema;
  /** @deprecated use `ComposeGetDefaultCommandRequest$outboundSchema` instead. */
  export const outboundSchema = ComposeGetDefaultCommandRequest$outboundSchema;
  /** @deprecated use `ComposeGetDefaultCommandRequest$Outbound` instead. */
  export type Outbound = ComposeGetDefaultCommandRequest$Outbound;
}

export function composeGetDefaultCommandRequestToJSON(
  composeGetDefaultCommandRequest: ComposeGetDefaultCommandRequest,
): string {
  return JSON.stringify(
    ComposeGetDefaultCommandRequest$outboundSchema.parse(
      composeGetDefaultCommandRequest,
    ),
  );
}

export function composeGetDefaultCommandRequestFromJSON(
  jsonString: string,
): SafeParseResult<ComposeGetDefaultCommandRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ComposeGetDefaultCommandRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComposeGetDefaultCommandRequest' from JSON`,
  );
}
