/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GiteaGetGiteaBranchesRequest = {
  owner: string;
  repositoryName: string;
  giteaId?: string | undefined;
};

/** @internal */
export const GiteaGetGiteaBranchesRequest$inboundSchema: z.ZodType<
  GiteaGetGiteaBranchesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  owner: z.string(),
  repositoryName: z.string(),
  giteaId: z.string().optional(),
});

/** @internal */
export type GiteaGetGiteaBranchesRequest$Outbound = {
  owner: string;
  repositoryName: string;
  giteaId?: string | undefined;
};

/** @internal */
export const GiteaGetGiteaBranchesRequest$outboundSchema: z.ZodType<
  GiteaGetGiteaBranchesRequest$Outbound,
  z.ZodTypeDef,
  GiteaGetGiteaBranchesRequest
> = z.object({
  owner: z.string(),
  repositoryName: z.string(),
  giteaId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GiteaGetGiteaBranchesRequest$ {
  /** @deprecated use `GiteaGetGiteaBranchesRequest$inboundSchema` instead. */
  export const inboundSchema = GiteaGetGiteaBranchesRequest$inboundSchema;
  /** @deprecated use `GiteaGetGiteaBranchesRequest$outboundSchema` instead. */
  export const outboundSchema = GiteaGetGiteaBranchesRequest$outboundSchema;
  /** @deprecated use `GiteaGetGiteaBranchesRequest$Outbound` instead. */
  export type Outbound = GiteaGetGiteaBranchesRequest$Outbound;
}

export function giteaGetGiteaBranchesRequestToJSON(
  giteaGetGiteaBranchesRequest: GiteaGetGiteaBranchesRequest,
): string {
  return JSON.stringify(
    GiteaGetGiteaBranchesRequest$outboundSchema.parse(
      giteaGetGiteaBranchesRequest,
    ),
  );
}

export function giteaGetGiteaBranchesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GiteaGetGiteaBranchesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GiteaGetGiteaBranchesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GiteaGetGiteaBranchesRequest' from JSON`,
  );
}
