/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MongoRemoveSecurity = {
  authorization: string;
};

export type MongoRemoveRequest = {
  mongoId: string;
};

export const MongoRemoveApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoRemoveApplicationStatus = ClosedEnum<
  typeof MongoRemoveApplicationStatus
>;

export type MongoRemoveHealthCheckSwarm = {
  test?: Array<string> | undefined;
  interval?: number | undefined;
  timeout?: number | undefined;
  startPeriod?: number | undefined;
  retries?: number | undefined;
};

export type MongoRemoveRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type MongoRemoveSpread = {
  spreadDescriptor: string;
};

export type MongoRemovePreference = {
  spread: MongoRemoveSpread;
};

export type MongoRemovePlatform = {
  architecture: string;
  os: string;
};

export type MongoRemovePlacementSwarm = {
  constraints?: Array<string> | undefined;
  preferences?: Array<MongoRemovePreference> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<MongoRemovePlatform> | undefined;
};

export type MongoRemoveUpdateConfigSwarm = {
  parallelism: number;
  delay?: number | undefined;
  failureAction?: string | undefined;
  monitor?: number | undefined;
  maxFailureRatio?: number | undefined;
  order: string;
};

export type MongoRemoveRollbackConfigSwarm = {
  parallelism: number;
  delay?: number | undefined;
  failureAction?: string | undefined;
  monitor?: number | undefined;
  maxFailureRatio?: number | undefined;
  order: string;
};

export type MongoRemoveReplicated = {
  replicas?: number | undefined;
};

export type MongoRemoveGlobal = {};

export type MongoRemoveReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type MongoRemoveGlobalJob = {};

export type MongoRemoveModeSwarm = {
  replicated?: MongoRemoveReplicated | undefined;
  global?: MongoRemoveGlobal | undefined;
  replicatedJob?: MongoRemoveReplicatedJob | undefined;
  globalJob?: MongoRemoveGlobalJob | undefined;
};

export type MongoRemoveDriverOpts = {};

export type MongoRemoveNetworkSwarm = {
  target?: string | undefined;
  aliases?: Array<string> | undefined;
  driverOpts?: MongoRemoveDriverOpts | undefined;
};

export type MongoRemoveProject = {
  projectId: string;
  name: string;
  description: string | null;
  createdAt: string;
  organizationId: string;
  env: string;
};

export type MongoRemoveEnvironment = {
  environmentId: string;
  name: string;
  description: string | null;
  createdAt: string;
  env: string;
  projectId: string;
  project: MongoRemoveProject;
};

export const MongoRemoveType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type MongoRemoveType = ClosedEnum<typeof MongoRemoveType>;

export const MongoRemoveServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type MongoRemoveServiceType = ClosedEnum<typeof MongoRemoveServiceType>;

export type MongoRemoveMount = {
  mountId: string;
  type: MongoRemoveType;
  hostPath: string | null;
  volumeName: string | null;
  filePath: string | null;
  content: string | null;
  serviceType: MongoRemoveServiceType;
  mountPath: string;
  applicationId: string | null;
  postgresId: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mysqlId: string | null;
  redisId: string | null;
  composeId: string | null;
};

export const MongoRemoveServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type MongoRemoveServerStatus = ClosedEnum<
  typeof MongoRemoveServerStatus
>;

export const MongoRemoveMetricsConfigEnum = {
  Null: "null",
} as const;
export type MongoRemoveMetricsConfigEnum = ClosedEnum<
  typeof MongoRemoveMetricsConfigEnum
>;

export type MongoRemoveMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | MongoRemoveMetricsConfigEnum;

export type MongoRemoveMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | MongoRemoveMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export type MongoRemoveServer = {
  serverId: string;
  name: string;
  description: string | null;
  ipAddress: string;
  port: number;
  username: string;
  appName: string;
  enableDockerCleanup: boolean;
  createdAt: string;
  organizationId: string;
  serverStatus: MongoRemoveServerStatus;
  command: string;
  sshKeyId: string | null;
  metricsConfig:
    | string
    | number
    | boolean
    | MongoRemoveMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
};

export const MongoRemoveBackupType = {
  Database: "database",
  Compose: "compose",
} as const;
export type MongoRemoveBackupType = ClosedEnum<typeof MongoRemoveBackupType>;

export const MongoRemoveDatabaseType = {
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mysql: "mysql",
  Mongo: "mongo",
  WebServer: "web-server",
} as const;
export type MongoRemoveDatabaseType = ClosedEnum<
  typeof MongoRemoveDatabaseType
>;

export const MongoRemoveMetadataEnum = {
  Null: "null",
} as const;
export type MongoRemoveMetadataEnum = ClosedEnum<
  typeof MongoRemoveMetadataEnum
>;

export type MongoRemovePostgres = {
  databaseUser: string;
};

export type MongoRemoveMariadb = {
  databaseUser: string;
  databasePassword: string;
};

export type MongoRemoveMongo = {
  databaseUser: string;
  databasePassword: string;
};

export type MongoRemoveMysql = {
  databaseRootPassword: string;
};

export type MongoRemoveMetadata = {
  postgres?: MongoRemovePostgres | undefined;
  mariadb?: MongoRemoveMariadb | undefined;
  mongo?: MongoRemoveMongo | undefined;
  mysql?: MongoRemoveMysql | undefined;
};

export type MongoRemoveMetadataUnion =
  | MongoRemoveMetadata
  | MongoRemoveMetadataEnum;

export type MongoRemoveBackup = {
  backupId: string;
  appName: string;
  schedule: string;
  enabled: boolean | null;
  database: string;
  prefix: string;
  serviceName: string | null;
  destinationId: string;
  keepLatestCount: number | null;
  backupType: MongoRemoveBackupType;
  databaseType: MongoRemoveDatabaseType;
  composeId: string | null;
  postgresId: string | null;
  mariadbId: string | null;
  mysqlId: string | null;
  mongoId: string | null;
  userId: string | null;
  metadata?: MongoRemoveMetadata | MongoRemoveMetadataEnum | null | undefined;
};

/**
 * Successful response
 */
export type MongoRemoveResponseBody = {
  mongoId: string;
  name: string;
  appName: string;
  description: string | null;
  databaseUser: string;
  databasePassword: string;
  dockerImage: string;
  command: string | null;
  env: string | null;
  memoryReservation: string | null;
  memoryLimit: string | null;
  cpuReservation: string | null;
  cpuLimit: string | null;
  externalPort: number | null;
  applicationStatus: MongoRemoveApplicationStatus;
  healthCheckSwarm: MongoRemoveHealthCheckSwarm | null;
  restartPolicySwarm: MongoRemoveRestartPolicySwarm | null;
  placementSwarm: MongoRemovePlacementSwarm | null;
  updateConfigSwarm: MongoRemoveUpdateConfigSwarm | null;
  rollbackConfigSwarm: MongoRemoveRollbackConfigSwarm | null;
  modeSwarm: MongoRemoveModeSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  networkSwarm: Array<MongoRemoveNetworkSwarm> | null;
  replicas: number;
  createdAt: string;
  environmentId: string;
  serverId: string | null;
  replicaSets: boolean | null;
  environment: MongoRemoveEnvironment;
  mounts: Array<MongoRemoveMount>;
  server: MongoRemoveServer | null;
  backups: Array<MongoRemoveBackup>;
};

export type MongoRemoveResponse = MongoRemoveResponseBody | models.ErrorT;

/** @internal */
export const MongoRemoveSecurity$inboundSchema: z.ZodType<
  MongoRemoveSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  Authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Authorization": "authorization",
  });
});

/** @internal */
export type MongoRemoveSecurity$Outbound = {
  Authorization: string;
};

/** @internal */
export const MongoRemoveSecurity$outboundSchema: z.ZodType<
  MongoRemoveSecurity$Outbound,
  z.ZodTypeDef,
  MongoRemoveSecurity
> = z.object({
  authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    authorization: "Authorization",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveSecurity$ {
  /** @deprecated use `MongoRemoveSecurity$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveSecurity$inboundSchema;
  /** @deprecated use `MongoRemoveSecurity$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveSecurity$outboundSchema;
  /** @deprecated use `MongoRemoveSecurity$Outbound` instead. */
  export type Outbound = MongoRemoveSecurity$Outbound;
}

export function mongoRemoveSecurityToJSON(
  mongoRemoveSecurity: MongoRemoveSecurity,
): string {
  return JSON.stringify(
    MongoRemoveSecurity$outboundSchema.parse(mongoRemoveSecurity),
  );
}

export function mongoRemoveSecurityFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveSecurity' from JSON`,
  );
}

/** @internal */
export const MongoRemoveRequest$inboundSchema: z.ZodType<
  MongoRemoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
});

/** @internal */
export type MongoRemoveRequest$Outbound = {
  mongoId: string;
};

/** @internal */
export const MongoRemoveRequest$outboundSchema: z.ZodType<
  MongoRemoveRequest$Outbound,
  z.ZodTypeDef,
  MongoRemoveRequest
> = z.object({
  mongoId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveRequest$ {
  /** @deprecated use `MongoRemoveRequest$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveRequest$inboundSchema;
  /** @deprecated use `MongoRemoveRequest$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveRequest$outboundSchema;
  /** @deprecated use `MongoRemoveRequest$Outbound` instead. */
  export type Outbound = MongoRemoveRequest$Outbound;
}

export function mongoRemoveRequestToJSON(
  mongoRemoveRequest: MongoRemoveRequest,
): string {
  return JSON.stringify(
    MongoRemoveRequest$outboundSchema.parse(mongoRemoveRequest),
  );
}

export function mongoRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveRequest' from JSON`,
  );
}

/** @internal */
export const MongoRemoveApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveApplicationStatus
> = z.nativeEnum(MongoRemoveApplicationStatus);

/** @internal */
export const MongoRemoveApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveApplicationStatus
> = MongoRemoveApplicationStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveApplicationStatus$ {
  /** @deprecated use `MongoRemoveApplicationStatus$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveApplicationStatus$inboundSchema;
  /** @deprecated use `MongoRemoveApplicationStatus$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveApplicationStatus$outboundSchema;
}

/** @internal */
export const MongoRemoveHealthCheckSwarm$inboundSchema: z.ZodType<
  MongoRemoveHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Test: z.array(z.string()).optional(),
  Interval: z.number().optional(),
  Timeout: z.number().optional(),
  StartPeriod: z.number().optional(),
  Retries: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Test": "test",
    "Interval": "interval",
    "Timeout": "timeout",
    "StartPeriod": "startPeriod",
    "Retries": "retries",
  });
});

/** @internal */
export type MongoRemoveHealthCheckSwarm$Outbound = {
  Test?: Array<string> | undefined;
  Interval?: number | undefined;
  Timeout?: number | undefined;
  StartPeriod?: number | undefined;
  Retries?: number | undefined;
};

/** @internal */
export const MongoRemoveHealthCheckSwarm$outboundSchema: z.ZodType<
  MongoRemoveHealthCheckSwarm$Outbound,
  z.ZodTypeDef,
  MongoRemoveHealthCheckSwarm
> = z.object({
  test: z.array(z.string()).optional(),
  interval: z.number().optional(),
  timeout: z.number().optional(),
  startPeriod: z.number().optional(),
  retries: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    test: "Test",
    interval: "Interval",
    timeout: "Timeout",
    startPeriod: "StartPeriod",
    retries: "Retries",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveHealthCheckSwarm$ {
  /** @deprecated use `MongoRemoveHealthCheckSwarm$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveHealthCheckSwarm$inboundSchema;
  /** @deprecated use `MongoRemoveHealthCheckSwarm$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveHealthCheckSwarm$outboundSchema;
  /** @deprecated use `MongoRemoveHealthCheckSwarm$Outbound` instead. */
  export type Outbound = MongoRemoveHealthCheckSwarm$Outbound;
}

export function mongoRemoveHealthCheckSwarmToJSON(
  mongoRemoveHealthCheckSwarm: MongoRemoveHealthCheckSwarm,
): string {
  return JSON.stringify(
    MongoRemoveHealthCheckSwarm$outboundSchema.parse(
      mongoRemoveHealthCheckSwarm,
    ),
  );
}

export function mongoRemoveHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveRestartPolicySwarm$inboundSchema: z.ZodType<
  MongoRemoveRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

/** @internal */
export type MongoRemoveRestartPolicySwarm$Outbound = {
  Condition?: string | undefined;
  Delay?: number | undefined;
  MaxAttempts?: number | undefined;
  Window?: number | undefined;
};

/** @internal */
export const MongoRemoveRestartPolicySwarm$outboundSchema: z.ZodType<
  MongoRemoveRestartPolicySwarm$Outbound,
  z.ZodTypeDef,
  MongoRemoveRestartPolicySwarm
> = z.object({
  condition: z.string().optional(),
  delay: z.number().optional(),
  maxAttempts: z.number().optional(),
  window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    condition: "Condition",
    delay: "Delay",
    maxAttempts: "MaxAttempts",
    window: "Window",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveRestartPolicySwarm$ {
  /** @deprecated use `MongoRemoveRestartPolicySwarm$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveRestartPolicySwarm$inboundSchema;
  /** @deprecated use `MongoRemoveRestartPolicySwarm$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveRestartPolicySwarm$outboundSchema;
  /** @deprecated use `MongoRemoveRestartPolicySwarm$Outbound` instead. */
  export type Outbound = MongoRemoveRestartPolicySwarm$Outbound;
}

export function mongoRemoveRestartPolicySwarmToJSON(
  mongoRemoveRestartPolicySwarm: MongoRemoveRestartPolicySwarm,
): string {
  return JSON.stringify(
    MongoRemoveRestartPolicySwarm$outboundSchema.parse(
      mongoRemoveRestartPolicySwarm,
    ),
  );
}

export function mongoRemoveRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveSpread$inboundSchema: z.ZodType<
  MongoRemoveSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

/** @internal */
export type MongoRemoveSpread$Outbound = {
  SpreadDescriptor: string;
};

/** @internal */
export const MongoRemoveSpread$outboundSchema: z.ZodType<
  MongoRemoveSpread$Outbound,
  z.ZodTypeDef,
  MongoRemoveSpread
> = z.object({
  spreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    spreadDescriptor: "SpreadDescriptor",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveSpread$ {
  /** @deprecated use `MongoRemoveSpread$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveSpread$inboundSchema;
  /** @deprecated use `MongoRemoveSpread$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveSpread$outboundSchema;
  /** @deprecated use `MongoRemoveSpread$Outbound` instead. */
  export type Outbound = MongoRemoveSpread$Outbound;
}

export function mongoRemoveSpreadToJSON(
  mongoRemoveSpread: MongoRemoveSpread,
): string {
  return JSON.stringify(
    MongoRemoveSpread$outboundSchema.parse(mongoRemoveSpread),
  );
}

export function mongoRemoveSpreadFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveSpread' from JSON`,
  );
}

/** @internal */
export const MongoRemovePreference$inboundSchema: z.ZodType<
  MongoRemovePreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => MongoRemoveSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

/** @internal */
export type MongoRemovePreference$Outbound = {
  Spread: MongoRemoveSpread$Outbound;
};

/** @internal */
export const MongoRemovePreference$outboundSchema: z.ZodType<
  MongoRemovePreference$Outbound,
  z.ZodTypeDef,
  MongoRemovePreference
> = z.object({
  spread: z.lazy(() => MongoRemoveSpread$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    spread: "Spread",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemovePreference$ {
  /** @deprecated use `MongoRemovePreference$inboundSchema` instead. */
  export const inboundSchema = MongoRemovePreference$inboundSchema;
  /** @deprecated use `MongoRemovePreference$outboundSchema` instead. */
  export const outboundSchema = MongoRemovePreference$outboundSchema;
  /** @deprecated use `MongoRemovePreference$Outbound` instead. */
  export type Outbound = MongoRemovePreference$Outbound;
}

export function mongoRemovePreferenceToJSON(
  mongoRemovePreference: MongoRemovePreference,
): string {
  return JSON.stringify(
    MongoRemovePreference$outboundSchema.parse(mongoRemovePreference),
  );
}

export function mongoRemovePreferenceFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePreference' from JSON`,
  );
}

/** @internal */
export const MongoRemovePlatform$inboundSchema: z.ZodType<
  MongoRemovePlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

/** @internal */
export type MongoRemovePlatform$Outbound = {
  Architecture: string;
  OS: string;
};

/** @internal */
export const MongoRemovePlatform$outboundSchema: z.ZodType<
  MongoRemovePlatform$Outbound,
  z.ZodTypeDef,
  MongoRemovePlatform
> = z.object({
  architecture: z.string(),
  os: z.string(),
}).transform((v) => {
  return remap$(v, {
    architecture: "Architecture",
    os: "OS",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemovePlatform$ {
  /** @deprecated use `MongoRemovePlatform$inboundSchema` instead. */
  export const inboundSchema = MongoRemovePlatform$inboundSchema;
  /** @deprecated use `MongoRemovePlatform$outboundSchema` instead. */
  export const outboundSchema = MongoRemovePlatform$outboundSchema;
  /** @deprecated use `MongoRemovePlatform$Outbound` instead. */
  export type Outbound = MongoRemovePlatform$Outbound;
}

export function mongoRemovePlatformToJSON(
  mongoRemovePlatform: MongoRemovePlatform,
): string {
  return JSON.stringify(
    MongoRemovePlatform$outboundSchema.parse(mongoRemovePlatform),
  );
}

export function mongoRemovePlatformFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePlatform' from JSON`,
  );
}

/** @internal */
export const MongoRemovePlacementSwarm$inboundSchema: z.ZodType<
  MongoRemovePlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  Preferences: z.array(z.lazy(() => MongoRemovePreference$inboundSchema))
    .optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => MongoRemovePlatform$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "Preferences": "preferences",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
  });
});

/** @internal */
export type MongoRemovePlacementSwarm$Outbound = {
  Constraints?: Array<string> | undefined;
  Preferences?: Array<MongoRemovePreference$Outbound> | undefined;
  MaxReplicas?: number | undefined;
  Platforms?: Array<MongoRemovePlatform$Outbound> | undefined;
};

/** @internal */
export const MongoRemovePlacementSwarm$outboundSchema: z.ZodType<
  MongoRemovePlacementSwarm$Outbound,
  z.ZodTypeDef,
  MongoRemovePlacementSwarm
> = z.object({
  constraints: z.array(z.string()).optional(),
  preferences: z.array(z.lazy(() => MongoRemovePreference$outboundSchema))
    .optional(),
  maxReplicas: z.number().optional(),
  platforms: z.array(z.lazy(() => MongoRemovePlatform$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    constraints: "Constraints",
    preferences: "Preferences",
    maxReplicas: "MaxReplicas",
    platforms: "Platforms",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemovePlacementSwarm$ {
  /** @deprecated use `MongoRemovePlacementSwarm$inboundSchema` instead. */
  export const inboundSchema = MongoRemovePlacementSwarm$inboundSchema;
  /** @deprecated use `MongoRemovePlacementSwarm$outboundSchema` instead. */
  export const outboundSchema = MongoRemovePlacementSwarm$outboundSchema;
  /** @deprecated use `MongoRemovePlacementSwarm$Outbound` instead. */
  export type Outbound = MongoRemovePlacementSwarm$Outbound;
}

export function mongoRemovePlacementSwarmToJSON(
  mongoRemovePlacementSwarm: MongoRemovePlacementSwarm,
): string {
  return JSON.stringify(
    MongoRemovePlacementSwarm$outboundSchema.parse(mongoRemovePlacementSwarm),
  );
}

export function mongoRemovePlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePlacementSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveUpdateConfigSwarm$inboundSchema: z.ZodType<
  MongoRemoveUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Parallelism: z.number(),
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  Monitor: z.number().optional(),
  MaxFailureRatio: z.number().optional(),
  Order: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Parallelism": "parallelism",
    "Delay": "delay",
    "FailureAction": "failureAction",
    "Monitor": "monitor",
    "MaxFailureRatio": "maxFailureRatio",
    "Order": "order",
  });
});

/** @internal */
export type MongoRemoveUpdateConfigSwarm$Outbound = {
  Parallelism: number;
  Delay?: number | undefined;
  FailureAction?: string | undefined;
  Monitor?: number | undefined;
  MaxFailureRatio?: number | undefined;
  Order: string;
};

/** @internal */
export const MongoRemoveUpdateConfigSwarm$outboundSchema: z.ZodType<
  MongoRemoveUpdateConfigSwarm$Outbound,
  z.ZodTypeDef,
  MongoRemoveUpdateConfigSwarm
> = z.object({
  parallelism: z.number(),
  delay: z.number().optional(),
  failureAction: z.string().optional(),
  monitor: z.number().optional(),
  maxFailureRatio: z.number().optional(),
  order: z.string(),
}).transform((v) => {
  return remap$(v, {
    parallelism: "Parallelism",
    delay: "Delay",
    failureAction: "FailureAction",
    monitor: "Monitor",
    maxFailureRatio: "MaxFailureRatio",
    order: "Order",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveUpdateConfigSwarm$ {
  /** @deprecated use `MongoRemoveUpdateConfigSwarm$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveUpdateConfigSwarm$inboundSchema;
  /** @deprecated use `MongoRemoveUpdateConfigSwarm$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveUpdateConfigSwarm$outboundSchema;
  /** @deprecated use `MongoRemoveUpdateConfigSwarm$Outbound` instead. */
  export type Outbound = MongoRemoveUpdateConfigSwarm$Outbound;
}

export function mongoRemoveUpdateConfigSwarmToJSON(
  mongoRemoveUpdateConfigSwarm: MongoRemoveUpdateConfigSwarm,
): string {
  return JSON.stringify(
    MongoRemoveUpdateConfigSwarm$outboundSchema.parse(
      mongoRemoveUpdateConfigSwarm,
    ),
  );
}

export function mongoRemoveUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveRollbackConfigSwarm$inboundSchema: z.ZodType<
  MongoRemoveRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Parallelism: z.number(),
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  Monitor: z.number().optional(),
  MaxFailureRatio: z.number().optional(),
  Order: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Parallelism": "parallelism",
    "Delay": "delay",
    "FailureAction": "failureAction",
    "Monitor": "monitor",
    "MaxFailureRatio": "maxFailureRatio",
    "Order": "order",
  });
});

/** @internal */
export type MongoRemoveRollbackConfigSwarm$Outbound = {
  Parallelism: number;
  Delay?: number | undefined;
  FailureAction?: string | undefined;
  Monitor?: number | undefined;
  MaxFailureRatio?: number | undefined;
  Order: string;
};

/** @internal */
export const MongoRemoveRollbackConfigSwarm$outboundSchema: z.ZodType<
  MongoRemoveRollbackConfigSwarm$Outbound,
  z.ZodTypeDef,
  MongoRemoveRollbackConfigSwarm
> = z.object({
  parallelism: z.number(),
  delay: z.number().optional(),
  failureAction: z.string().optional(),
  monitor: z.number().optional(),
  maxFailureRatio: z.number().optional(),
  order: z.string(),
}).transform((v) => {
  return remap$(v, {
    parallelism: "Parallelism",
    delay: "Delay",
    failureAction: "FailureAction",
    monitor: "Monitor",
    maxFailureRatio: "MaxFailureRatio",
    order: "Order",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveRollbackConfigSwarm$ {
  /** @deprecated use `MongoRemoveRollbackConfigSwarm$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveRollbackConfigSwarm$inboundSchema;
  /** @deprecated use `MongoRemoveRollbackConfigSwarm$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveRollbackConfigSwarm$outboundSchema;
  /** @deprecated use `MongoRemoveRollbackConfigSwarm$Outbound` instead. */
  export type Outbound = MongoRemoveRollbackConfigSwarm$Outbound;
}

export function mongoRemoveRollbackConfigSwarmToJSON(
  mongoRemoveRollbackConfigSwarm: MongoRemoveRollbackConfigSwarm,
): string {
  return JSON.stringify(
    MongoRemoveRollbackConfigSwarm$outboundSchema.parse(
      mongoRemoveRollbackConfigSwarm,
    ),
  );
}

export function mongoRemoveRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveReplicated$inboundSchema: z.ZodType<
  MongoRemoveReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

/** @internal */
export type MongoRemoveReplicated$Outbound = {
  Replicas?: number | undefined;
};

/** @internal */
export const MongoRemoveReplicated$outboundSchema: z.ZodType<
  MongoRemoveReplicated$Outbound,
  z.ZodTypeDef,
  MongoRemoveReplicated
> = z.object({
  replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    replicas: "Replicas",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveReplicated$ {
  /** @deprecated use `MongoRemoveReplicated$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveReplicated$inboundSchema;
  /** @deprecated use `MongoRemoveReplicated$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveReplicated$outboundSchema;
  /** @deprecated use `MongoRemoveReplicated$Outbound` instead. */
  export type Outbound = MongoRemoveReplicated$Outbound;
}

export function mongoRemoveReplicatedToJSON(
  mongoRemoveReplicated: MongoRemoveReplicated,
): string {
  return JSON.stringify(
    MongoRemoveReplicated$outboundSchema.parse(mongoRemoveReplicated),
  );
}

export function mongoRemoveReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveReplicated' from JSON`,
  );
}

/** @internal */
export const MongoRemoveGlobal$inboundSchema: z.ZodType<
  MongoRemoveGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type MongoRemoveGlobal$Outbound = {};

/** @internal */
export const MongoRemoveGlobal$outboundSchema: z.ZodType<
  MongoRemoveGlobal$Outbound,
  z.ZodTypeDef,
  MongoRemoveGlobal
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveGlobal$ {
  /** @deprecated use `MongoRemoveGlobal$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveGlobal$inboundSchema;
  /** @deprecated use `MongoRemoveGlobal$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveGlobal$outboundSchema;
  /** @deprecated use `MongoRemoveGlobal$Outbound` instead. */
  export type Outbound = MongoRemoveGlobal$Outbound;
}

export function mongoRemoveGlobalToJSON(
  mongoRemoveGlobal: MongoRemoveGlobal,
): string {
  return JSON.stringify(
    MongoRemoveGlobal$outboundSchema.parse(mongoRemoveGlobal),
  );
}

export function mongoRemoveGlobalFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveGlobal' from JSON`,
  );
}

/** @internal */
export const MongoRemoveReplicatedJob$inboundSchema: z.ZodType<
  MongoRemoveReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

/** @internal */
export type MongoRemoveReplicatedJob$Outbound = {
  MaxConcurrent?: number | undefined;
  TotalCompletions?: number | undefined;
};

/** @internal */
export const MongoRemoveReplicatedJob$outboundSchema: z.ZodType<
  MongoRemoveReplicatedJob$Outbound,
  z.ZodTypeDef,
  MongoRemoveReplicatedJob
> = z.object({
  maxConcurrent: z.number().optional(),
  totalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    maxConcurrent: "MaxConcurrent",
    totalCompletions: "TotalCompletions",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveReplicatedJob$ {
  /** @deprecated use `MongoRemoveReplicatedJob$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveReplicatedJob$inboundSchema;
  /** @deprecated use `MongoRemoveReplicatedJob$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveReplicatedJob$outboundSchema;
  /** @deprecated use `MongoRemoveReplicatedJob$Outbound` instead. */
  export type Outbound = MongoRemoveReplicatedJob$Outbound;
}

export function mongoRemoveReplicatedJobToJSON(
  mongoRemoveReplicatedJob: MongoRemoveReplicatedJob,
): string {
  return JSON.stringify(
    MongoRemoveReplicatedJob$outboundSchema.parse(mongoRemoveReplicatedJob),
  );
}

export function mongoRemoveReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveReplicatedJob' from JSON`,
  );
}

/** @internal */
export const MongoRemoveGlobalJob$inboundSchema: z.ZodType<
  MongoRemoveGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type MongoRemoveGlobalJob$Outbound = {};

/** @internal */
export const MongoRemoveGlobalJob$outboundSchema: z.ZodType<
  MongoRemoveGlobalJob$Outbound,
  z.ZodTypeDef,
  MongoRemoveGlobalJob
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveGlobalJob$ {
  /** @deprecated use `MongoRemoveGlobalJob$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveGlobalJob$inboundSchema;
  /** @deprecated use `MongoRemoveGlobalJob$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveGlobalJob$outboundSchema;
  /** @deprecated use `MongoRemoveGlobalJob$Outbound` instead. */
  export type Outbound = MongoRemoveGlobalJob$Outbound;
}

export function mongoRemoveGlobalJobToJSON(
  mongoRemoveGlobalJob: MongoRemoveGlobalJob,
): string {
  return JSON.stringify(
    MongoRemoveGlobalJob$outboundSchema.parse(mongoRemoveGlobalJob),
  );
}

export function mongoRemoveGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveGlobalJob' from JSON`,
  );
}

/** @internal */
export const MongoRemoveModeSwarm$inboundSchema: z.ZodType<
  MongoRemoveModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicated: z.lazy(() => MongoRemoveReplicated$inboundSchema).optional(),
  Global: z.lazy(() => MongoRemoveGlobal$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => MongoRemoveReplicatedJob$inboundSchema)
    .optional(),
  GlobalJob: z.lazy(() => MongoRemoveGlobalJob$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicated": "replicated",
    "Global": "global",
    "ReplicatedJob": "replicatedJob",
    "GlobalJob": "globalJob",
  });
});

/** @internal */
export type MongoRemoveModeSwarm$Outbound = {
  Replicated?: MongoRemoveReplicated$Outbound | undefined;
  Global?: MongoRemoveGlobal$Outbound | undefined;
  ReplicatedJob?: MongoRemoveReplicatedJob$Outbound | undefined;
  GlobalJob?: MongoRemoveGlobalJob$Outbound | undefined;
};

/** @internal */
export const MongoRemoveModeSwarm$outboundSchema: z.ZodType<
  MongoRemoveModeSwarm$Outbound,
  z.ZodTypeDef,
  MongoRemoveModeSwarm
> = z.object({
  replicated: z.lazy(() => MongoRemoveReplicated$outboundSchema).optional(),
  global: z.lazy(() => MongoRemoveGlobal$outboundSchema).optional(),
  replicatedJob: z.lazy(() => MongoRemoveReplicatedJob$outboundSchema)
    .optional(),
  globalJob: z.lazy(() => MongoRemoveGlobalJob$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    replicated: "Replicated",
    global: "Global",
    replicatedJob: "ReplicatedJob",
    globalJob: "GlobalJob",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveModeSwarm$ {
  /** @deprecated use `MongoRemoveModeSwarm$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveModeSwarm$inboundSchema;
  /** @deprecated use `MongoRemoveModeSwarm$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveModeSwarm$outboundSchema;
  /** @deprecated use `MongoRemoveModeSwarm$Outbound` instead. */
  export type Outbound = MongoRemoveModeSwarm$Outbound;
}

export function mongoRemoveModeSwarmToJSON(
  mongoRemoveModeSwarm: MongoRemoveModeSwarm,
): string {
  return JSON.stringify(
    MongoRemoveModeSwarm$outboundSchema.parse(mongoRemoveModeSwarm),
  );
}

export function mongoRemoveModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveModeSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveDriverOpts$inboundSchema: z.ZodType<
  MongoRemoveDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type MongoRemoveDriverOpts$Outbound = {};

/** @internal */
export const MongoRemoveDriverOpts$outboundSchema: z.ZodType<
  MongoRemoveDriverOpts$Outbound,
  z.ZodTypeDef,
  MongoRemoveDriverOpts
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveDriverOpts$ {
  /** @deprecated use `MongoRemoveDriverOpts$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveDriverOpts$inboundSchema;
  /** @deprecated use `MongoRemoveDriverOpts$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveDriverOpts$outboundSchema;
  /** @deprecated use `MongoRemoveDriverOpts$Outbound` instead. */
  export type Outbound = MongoRemoveDriverOpts$Outbound;
}

export function mongoRemoveDriverOptsToJSON(
  mongoRemoveDriverOpts: MongoRemoveDriverOpts,
): string {
  return JSON.stringify(
    MongoRemoveDriverOpts$outboundSchema.parse(mongoRemoveDriverOpts),
  );
}

export function mongoRemoveDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveDriverOpts' from JSON`,
  );
}

/** @internal */
export const MongoRemoveNetworkSwarm$inboundSchema: z.ZodType<
  MongoRemoveNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Target: z.string().optional(),
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => MongoRemoveDriverOpts$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "Target": "target",
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
  });
});

/** @internal */
export type MongoRemoveNetworkSwarm$Outbound = {
  Target?: string | undefined;
  Aliases?: Array<string> | undefined;
  DriverOpts?: MongoRemoveDriverOpts$Outbound | undefined;
};

/** @internal */
export const MongoRemoveNetworkSwarm$outboundSchema: z.ZodType<
  MongoRemoveNetworkSwarm$Outbound,
  z.ZodTypeDef,
  MongoRemoveNetworkSwarm
> = z.object({
  target: z.string().optional(),
  aliases: z.array(z.string()).optional(),
  driverOpts: z.lazy(() => MongoRemoveDriverOpts$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    target: "Target",
    aliases: "Aliases",
    driverOpts: "DriverOpts",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveNetworkSwarm$ {
  /** @deprecated use `MongoRemoveNetworkSwarm$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveNetworkSwarm$inboundSchema;
  /** @deprecated use `MongoRemoveNetworkSwarm$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveNetworkSwarm$outboundSchema;
  /** @deprecated use `MongoRemoveNetworkSwarm$Outbound` instead. */
  export type Outbound = MongoRemoveNetworkSwarm$Outbound;
}

export function mongoRemoveNetworkSwarmToJSON(
  mongoRemoveNetworkSwarm: MongoRemoveNetworkSwarm,
): string {
  return JSON.stringify(
    MongoRemoveNetworkSwarm$outboundSchema.parse(mongoRemoveNetworkSwarm),
  );
}

export function mongoRemoveNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveProject$inboundSchema: z.ZodType<
  MongoRemoveProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectId: z.string(),
  name: z.string(),
  description: z.nullable(z.string()),
  createdAt: z.string(),
  organizationId: z.string(),
  env: z.string(),
});

/** @internal */
export type MongoRemoveProject$Outbound = {
  projectId: string;
  name: string;
  description: string | null;
  createdAt: string;
  organizationId: string;
  env: string;
};

/** @internal */
export const MongoRemoveProject$outboundSchema: z.ZodType<
  MongoRemoveProject$Outbound,
  z.ZodTypeDef,
  MongoRemoveProject
> = z.object({
  projectId: z.string(),
  name: z.string(),
  description: z.nullable(z.string()),
  createdAt: z.string(),
  organizationId: z.string(),
  env: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveProject$ {
  /** @deprecated use `MongoRemoveProject$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveProject$inboundSchema;
  /** @deprecated use `MongoRemoveProject$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveProject$outboundSchema;
  /** @deprecated use `MongoRemoveProject$Outbound` instead. */
  export type Outbound = MongoRemoveProject$Outbound;
}

export function mongoRemoveProjectToJSON(
  mongoRemoveProject: MongoRemoveProject,
): string {
  return JSON.stringify(
    MongoRemoveProject$outboundSchema.parse(mongoRemoveProject),
  );
}

export function mongoRemoveProjectFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveProject' from JSON`,
  );
}

/** @internal */
export const MongoRemoveEnvironment$inboundSchema: z.ZodType<
  MongoRemoveEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  environmentId: z.string(),
  name: z.string(),
  description: z.nullable(z.string()),
  createdAt: z.string(),
  env: z.string(),
  projectId: z.string(),
  project: z.lazy(() => MongoRemoveProject$inboundSchema),
});

/** @internal */
export type MongoRemoveEnvironment$Outbound = {
  environmentId: string;
  name: string;
  description: string | null;
  createdAt: string;
  env: string;
  projectId: string;
  project: MongoRemoveProject$Outbound;
};

/** @internal */
export const MongoRemoveEnvironment$outboundSchema: z.ZodType<
  MongoRemoveEnvironment$Outbound,
  z.ZodTypeDef,
  MongoRemoveEnvironment
> = z.object({
  environmentId: z.string(),
  name: z.string(),
  description: z.nullable(z.string()),
  createdAt: z.string(),
  env: z.string(),
  projectId: z.string(),
  project: z.lazy(() => MongoRemoveProject$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveEnvironment$ {
  /** @deprecated use `MongoRemoveEnvironment$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveEnvironment$inboundSchema;
  /** @deprecated use `MongoRemoveEnvironment$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveEnvironment$outboundSchema;
  /** @deprecated use `MongoRemoveEnvironment$Outbound` instead. */
  export type Outbound = MongoRemoveEnvironment$Outbound;
}

export function mongoRemoveEnvironmentToJSON(
  mongoRemoveEnvironment: MongoRemoveEnvironment,
): string {
  return JSON.stringify(
    MongoRemoveEnvironment$outboundSchema.parse(mongoRemoveEnvironment),
  );
}

export function mongoRemoveEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveEnvironment' from JSON`,
  );
}

/** @internal */
export const MongoRemoveType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveType
> = z.nativeEnum(MongoRemoveType);

/** @internal */
export const MongoRemoveType$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveType
> = MongoRemoveType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveType$ {
  /** @deprecated use `MongoRemoveType$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveType$inboundSchema;
  /** @deprecated use `MongoRemoveType$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveType$outboundSchema;
}

/** @internal */
export const MongoRemoveServiceType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveServiceType
> = z.nativeEnum(MongoRemoveServiceType);

/** @internal */
export const MongoRemoveServiceType$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveServiceType
> = MongoRemoveServiceType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveServiceType$ {
  /** @deprecated use `MongoRemoveServiceType$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveServiceType$inboundSchema;
  /** @deprecated use `MongoRemoveServiceType$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveServiceType$outboundSchema;
}

/** @internal */
export const MongoRemoveMount$inboundSchema: z.ZodType<
  MongoRemoveMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  mountId: z.string(),
  type: MongoRemoveType$inboundSchema,
  hostPath: z.nullable(z.string()),
  volumeName: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  content: z.nullable(z.string()),
  serviceType: MongoRemoveServiceType$inboundSchema,
  mountPath: z.string(),
  applicationId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
});

/** @internal */
export type MongoRemoveMount$Outbound = {
  mountId: string;
  type: string;
  hostPath: string | null;
  volumeName: string | null;
  filePath: string | null;
  content: string | null;
  serviceType: string;
  mountPath: string;
  applicationId: string | null;
  postgresId: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mysqlId: string | null;
  redisId: string | null;
  composeId: string | null;
};

/** @internal */
export const MongoRemoveMount$outboundSchema: z.ZodType<
  MongoRemoveMount$Outbound,
  z.ZodTypeDef,
  MongoRemoveMount
> = z.object({
  mountId: z.string(),
  type: MongoRemoveType$outboundSchema,
  hostPath: z.nullable(z.string()),
  volumeName: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  content: z.nullable(z.string()),
  serviceType: MongoRemoveServiceType$outboundSchema,
  mountPath: z.string(),
  applicationId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMount$ {
  /** @deprecated use `MongoRemoveMount$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMount$inboundSchema;
  /** @deprecated use `MongoRemoveMount$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMount$outboundSchema;
  /** @deprecated use `MongoRemoveMount$Outbound` instead. */
  export type Outbound = MongoRemoveMount$Outbound;
}

export function mongoRemoveMountToJSON(
  mongoRemoveMount: MongoRemoveMount,
): string {
  return JSON.stringify(
    MongoRemoveMount$outboundSchema.parse(mongoRemoveMount),
  );
}

export function mongoRemoveMountFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMount' from JSON`,
  );
}

/** @internal */
export const MongoRemoveServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveServerStatus
> = z.nativeEnum(MongoRemoveServerStatus);

/** @internal */
export const MongoRemoveServerStatus$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveServerStatus
> = MongoRemoveServerStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveServerStatus$ {
  /** @deprecated use `MongoRemoveServerStatus$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveServerStatus$inboundSchema;
  /** @deprecated use `MongoRemoveServerStatus$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveServerStatus$outboundSchema;
}

/** @internal */
export const MongoRemoveMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveMetricsConfigEnum
> = z.nativeEnum(MongoRemoveMetricsConfigEnum);

/** @internal */
export const MongoRemoveMetricsConfigEnum$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveMetricsConfigEnum
> = MongoRemoveMetricsConfigEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMetricsConfigEnum$ {
  /** @deprecated use `MongoRemoveMetricsConfigEnum$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMetricsConfigEnum$inboundSchema;
  /** @deprecated use `MongoRemoveMetricsConfigEnum$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMetricsConfigEnum$outboundSchema;
}

/** @internal */
export const MongoRemoveMetricsConfigUnion1$inboundSchema: z.ZodType<
  MongoRemoveMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  MongoRemoveMetricsConfigEnum$inboundSchema,
]);

/** @internal */
export type MongoRemoveMetricsConfigUnion1$Outbound =
  | string
  | number
  | boolean
  | string;

/** @internal */
export const MongoRemoveMetricsConfigUnion1$outboundSchema: z.ZodType<
  MongoRemoveMetricsConfigUnion1$Outbound,
  z.ZodTypeDef,
  MongoRemoveMetricsConfigUnion1
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  MongoRemoveMetricsConfigEnum$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMetricsConfigUnion1$ {
  /** @deprecated use `MongoRemoveMetricsConfigUnion1$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMetricsConfigUnion1$inboundSchema;
  /** @deprecated use `MongoRemoveMetricsConfigUnion1$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMetricsConfigUnion1$outboundSchema;
  /** @deprecated use `MongoRemoveMetricsConfigUnion1$Outbound` instead. */
  export type Outbound = MongoRemoveMetricsConfigUnion1$Outbound;
}

export function mongoRemoveMetricsConfigUnion1ToJSON(
  mongoRemoveMetricsConfigUnion1: MongoRemoveMetricsConfigUnion1,
): string {
  return JSON.stringify(
    MongoRemoveMetricsConfigUnion1$outboundSchema.parse(
      mongoRemoveMetricsConfigUnion1,
    ),
  );
}

export function mongoRemoveMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMetricsConfigUnion2$inboundSchema: z.ZodType<
  MongoRemoveMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    MongoRemoveMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

/** @internal */
export type MongoRemoveMetricsConfigUnion2$Outbound =
  | string
  | number
  | boolean
  | string
  | Array<any>
  | { [k: string]: any };

/** @internal */
export const MongoRemoveMetricsConfigUnion2$outboundSchema: z.ZodType<
  MongoRemoveMetricsConfigUnion2$Outbound,
  z.ZodTypeDef,
  MongoRemoveMetricsConfigUnion2
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    MongoRemoveMetricsConfigEnum$outboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMetricsConfigUnion2$ {
  /** @deprecated use `MongoRemoveMetricsConfigUnion2$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMetricsConfigUnion2$inboundSchema;
  /** @deprecated use `MongoRemoveMetricsConfigUnion2$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMetricsConfigUnion2$outboundSchema;
  /** @deprecated use `MongoRemoveMetricsConfigUnion2$Outbound` instead. */
  export type Outbound = MongoRemoveMetricsConfigUnion2$Outbound;
}

export function mongoRemoveMetricsConfigUnion2ToJSON(
  mongoRemoveMetricsConfigUnion2: MongoRemoveMetricsConfigUnion2,
): string {
  return JSON.stringify(
    MongoRemoveMetricsConfigUnion2$outboundSchema.parse(
      mongoRemoveMetricsConfigUnion2,
    ),
  );
}

export function mongoRemoveMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const MongoRemoveServer$inboundSchema: z.ZodType<
  MongoRemoveServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  serverId: z.string(),
  name: z.string(),
  description: z.nullable(z.string()),
  ipAddress: z.string(),
  port: z.number(),
  username: z.string(),
  appName: z.string(),
  enableDockerCleanup: z.boolean(),
  createdAt: z.string(),
  organizationId: z.string(),
  serverStatus: MongoRemoveServerStatus$inboundSchema,
  command: z.string(),
  sshKeyId: z.nullable(z.string()),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      MongoRemoveMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
});

/** @internal */
export type MongoRemoveServer$Outbound = {
  serverId: string;
  name: string;
  description: string | null;
  ipAddress: string;
  port: number;
  username: string;
  appName: string;
  enableDockerCleanup: boolean;
  createdAt: string;
  organizationId: string;
  serverStatus: string;
  command: string;
  sshKeyId: string | null;
  metricsConfig: string | number | boolean | string | Array<any> | {
    [k: string]: any;
  };
};

/** @internal */
export const MongoRemoveServer$outboundSchema: z.ZodType<
  MongoRemoveServer$Outbound,
  z.ZodTypeDef,
  MongoRemoveServer
> = z.object({
  serverId: z.string(),
  name: z.string(),
  description: z.nullable(z.string()),
  ipAddress: z.string(),
  port: z.number(),
  username: z.string(),
  appName: z.string(),
  enableDockerCleanup: z.boolean(),
  createdAt: z.string(),
  organizationId: z.string(),
  serverStatus: MongoRemoveServerStatus$outboundSchema,
  command: z.string(),
  sshKeyId: z.nullable(z.string()),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      MongoRemoveMetricsConfigEnum$outboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveServer$ {
  /** @deprecated use `MongoRemoveServer$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveServer$inboundSchema;
  /** @deprecated use `MongoRemoveServer$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveServer$outboundSchema;
  /** @deprecated use `MongoRemoveServer$Outbound` instead. */
  export type Outbound = MongoRemoveServer$Outbound;
}

export function mongoRemoveServerToJSON(
  mongoRemoveServer: MongoRemoveServer,
): string {
  return JSON.stringify(
    MongoRemoveServer$outboundSchema.parse(mongoRemoveServer),
  );
}

export function mongoRemoveServerFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveServer' from JSON`,
  );
}

/** @internal */
export const MongoRemoveBackupType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveBackupType
> = z.nativeEnum(MongoRemoveBackupType);

/** @internal */
export const MongoRemoveBackupType$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveBackupType
> = MongoRemoveBackupType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveBackupType$ {
  /** @deprecated use `MongoRemoveBackupType$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveBackupType$inboundSchema;
  /** @deprecated use `MongoRemoveBackupType$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveBackupType$outboundSchema;
}

/** @internal */
export const MongoRemoveDatabaseType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveDatabaseType
> = z.nativeEnum(MongoRemoveDatabaseType);

/** @internal */
export const MongoRemoveDatabaseType$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveDatabaseType
> = MongoRemoveDatabaseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveDatabaseType$ {
  /** @deprecated use `MongoRemoveDatabaseType$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveDatabaseType$inboundSchema;
  /** @deprecated use `MongoRemoveDatabaseType$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveDatabaseType$outboundSchema;
}

/** @internal */
export const MongoRemoveMetadataEnum$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveMetadataEnum
> = z.nativeEnum(MongoRemoveMetadataEnum);

/** @internal */
export const MongoRemoveMetadataEnum$outboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveMetadataEnum
> = MongoRemoveMetadataEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMetadataEnum$ {
  /** @deprecated use `MongoRemoveMetadataEnum$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMetadataEnum$inboundSchema;
  /** @deprecated use `MongoRemoveMetadataEnum$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMetadataEnum$outboundSchema;
}

/** @internal */
export const MongoRemovePostgres$inboundSchema: z.ZodType<
  MongoRemovePostgres,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
});

/** @internal */
export type MongoRemovePostgres$Outbound = {
  databaseUser: string;
};

/** @internal */
export const MongoRemovePostgres$outboundSchema: z.ZodType<
  MongoRemovePostgres$Outbound,
  z.ZodTypeDef,
  MongoRemovePostgres
> = z.object({
  databaseUser: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemovePostgres$ {
  /** @deprecated use `MongoRemovePostgres$inboundSchema` instead. */
  export const inboundSchema = MongoRemovePostgres$inboundSchema;
  /** @deprecated use `MongoRemovePostgres$outboundSchema` instead. */
  export const outboundSchema = MongoRemovePostgres$outboundSchema;
  /** @deprecated use `MongoRemovePostgres$Outbound` instead. */
  export type Outbound = MongoRemovePostgres$Outbound;
}

export function mongoRemovePostgresToJSON(
  mongoRemovePostgres: MongoRemovePostgres,
): string {
  return JSON.stringify(
    MongoRemovePostgres$outboundSchema.parse(mongoRemovePostgres),
  );
}

export function mongoRemovePostgresFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePostgres, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePostgres$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePostgres' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMariadb$inboundSchema: z.ZodType<
  MongoRemoveMariadb,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
  databasePassword: z.string(),
});

/** @internal */
export type MongoRemoveMariadb$Outbound = {
  databaseUser: string;
  databasePassword: string;
};

/** @internal */
export const MongoRemoveMariadb$outboundSchema: z.ZodType<
  MongoRemoveMariadb$Outbound,
  z.ZodTypeDef,
  MongoRemoveMariadb
> = z.object({
  databaseUser: z.string(),
  databasePassword: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMariadb$ {
  /** @deprecated use `MongoRemoveMariadb$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMariadb$inboundSchema;
  /** @deprecated use `MongoRemoveMariadb$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMariadb$outboundSchema;
  /** @deprecated use `MongoRemoveMariadb$Outbound` instead. */
  export type Outbound = MongoRemoveMariadb$Outbound;
}

export function mongoRemoveMariadbToJSON(
  mongoRemoveMariadb: MongoRemoveMariadb,
): string {
  return JSON.stringify(
    MongoRemoveMariadb$outboundSchema.parse(mongoRemoveMariadb),
  );
}

export function mongoRemoveMariadbFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMariadb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMariadb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMariadb' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMongo$inboundSchema: z.ZodType<
  MongoRemoveMongo,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
  databasePassword: z.string(),
});

/** @internal */
export type MongoRemoveMongo$Outbound = {
  databaseUser: string;
  databasePassword: string;
};

/** @internal */
export const MongoRemoveMongo$outboundSchema: z.ZodType<
  MongoRemoveMongo$Outbound,
  z.ZodTypeDef,
  MongoRemoveMongo
> = z.object({
  databaseUser: z.string(),
  databasePassword: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMongo$ {
  /** @deprecated use `MongoRemoveMongo$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMongo$inboundSchema;
  /** @deprecated use `MongoRemoveMongo$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMongo$outboundSchema;
  /** @deprecated use `MongoRemoveMongo$Outbound` instead. */
  export type Outbound = MongoRemoveMongo$Outbound;
}

export function mongoRemoveMongoToJSON(
  mongoRemoveMongo: MongoRemoveMongo,
): string {
  return JSON.stringify(
    MongoRemoveMongo$outboundSchema.parse(mongoRemoveMongo),
  );
}

export function mongoRemoveMongoFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMongo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMongo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMongo' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMysql$inboundSchema: z.ZodType<
  MongoRemoveMysql,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseRootPassword: z.string(),
});

/** @internal */
export type MongoRemoveMysql$Outbound = {
  databaseRootPassword: string;
};

/** @internal */
export const MongoRemoveMysql$outboundSchema: z.ZodType<
  MongoRemoveMysql$Outbound,
  z.ZodTypeDef,
  MongoRemoveMysql
> = z.object({
  databaseRootPassword: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMysql$ {
  /** @deprecated use `MongoRemoveMysql$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMysql$inboundSchema;
  /** @deprecated use `MongoRemoveMysql$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMysql$outboundSchema;
  /** @deprecated use `MongoRemoveMysql$Outbound` instead. */
  export type Outbound = MongoRemoveMysql$Outbound;
}

export function mongoRemoveMysqlToJSON(
  mongoRemoveMysql: MongoRemoveMysql,
): string {
  return JSON.stringify(
    MongoRemoveMysql$outboundSchema.parse(mongoRemoveMysql),
  );
}

export function mongoRemoveMysqlFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMysql, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMysql$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMysql' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMetadata$inboundSchema: z.ZodType<
  MongoRemoveMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  postgres: z.lazy(() => MongoRemovePostgres$inboundSchema).optional(),
  mariadb: z.lazy(() => MongoRemoveMariadb$inboundSchema).optional(),
  mongo: z.lazy(() => MongoRemoveMongo$inboundSchema).optional(),
  mysql: z.lazy(() => MongoRemoveMysql$inboundSchema).optional(),
});

/** @internal */
export type MongoRemoveMetadata$Outbound = {
  postgres?: MongoRemovePostgres$Outbound | undefined;
  mariadb?: MongoRemoveMariadb$Outbound | undefined;
  mongo?: MongoRemoveMongo$Outbound | undefined;
  mysql?: MongoRemoveMysql$Outbound | undefined;
};

/** @internal */
export const MongoRemoveMetadata$outboundSchema: z.ZodType<
  MongoRemoveMetadata$Outbound,
  z.ZodTypeDef,
  MongoRemoveMetadata
> = z.object({
  postgres: z.lazy(() => MongoRemovePostgres$outboundSchema).optional(),
  mariadb: z.lazy(() => MongoRemoveMariadb$outboundSchema).optional(),
  mongo: z.lazy(() => MongoRemoveMongo$outboundSchema).optional(),
  mysql: z.lazy(() => MongoRemoveMysql$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMetadata$ {
  /** @deprecated use `MongoRemoveMetadata$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMetadata$inboundSchema;
  /** @deprecated use `MongoRemoveMetadata$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMetadata$outboundSchema;
  /** @deprecated use `MongoRemoveMetadata$Outbound` instead. */
  export type Outbound = MongoRemoveMetadata$Outbound;
}

export function mongoRemoveMetadataToJSON(
  mongoRemoveMetadata: MongoRemoveMetadata,
): string {
  return JSON.stringify(
    MongoRemoveMetadata$outboundSchema.parse(mongoRemoveMetadata),
  );
}

export function mongoRemoveMetadataFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetadata' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMetadataUnion$inboundSchema: z.ZodType<
  MongoRemoveMetadataUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoRemoveMetadata$inboundSchema),
  MongoRemoveMetadataEnum$inboundSchema,
]);

/** @internal */
export type MongoRemoveMetadataUnion$Outbound =
  | MongoRemoveMetadata$Outbound
  | string;

/** @internal */
export const MongoRemoveMetadataUnion$outboundSchema: z.ZodType<
  MongoRemoveMetadataUnion$Outbound,
  z.ZodTypeDef,
  MongoRemoveMetadataUnion
> = z.union([
  z.lazy(() => MongoRemoveMetadata$outboundSchema),
  MongoRemoveMetadataEnum$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveMetadataUnion$ {
  /** @deprecated use `MongoRemoveMetadataUnion$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveMetadataUnion$inboundSchema;
  /** @deprecated use `MongoRemoveMetadataUnion$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveMetadataUnion$outboundSchema;
  /** @deprecated use `MongoRemoveMetadataUnion$Outbound` instead. */
  export type Outbound = MongoRemoveMetadataUnion$Outbound;
}

export function mongoRemoveMetadataUnionToJSON(
  mongoRemoveMetadataUnion: MongoRemoveMetadataUnion,
): string {
  return JSON.stringify(
    MongoRemoveMetadataUnion$outboundSchema.parse(mongoRemoveMetadataUnion),
  );
}

export function mongoRemoveMetadataUnionFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetadataUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetadataUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetadataUnion' from JSON`,
  );
}

/** @internal */
export const MongoRemoveBackup$inboundSchema: z.ZodType<
  MongoRemoveBackup,
  z.ZodTypeDef,
  unknown
> = z.object({
  backupId: z.string(),
  appName: z.string(),
  schedule: z.string(),
  enabled: z.nullable(z.boolean()),
  database: z.string(),
  prefix: z.string(),
  serviceName: z.nullable(z.string()),
  destinationId: z.string(),
  keepLatestCount: z.nullable(z.number()),
  backupType: MongoRemoveBackupType$inboundSchema,
  databaseType: MongoRemoveDatabaseType$inboundSchema,
  composeId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  userId: z.nullable(z.string()),
  metadata: z.nullable(
    z.union([
      z.lazy(() => MongoRemoveMetadata$inboundSchema),
      MongoRemoveMetadataEnum$inboundSchema,
    ]),
  ).optional(),
});

/** @internal */
export type MongoRemoveBackup$Outbound = {
  backupId: string;
  appName: string;
  schedule: string;
  enabled: boolean | null;
  database: string;
  prefix: string;
  serviceName: string | null;
  destinationId: string;
  keepLatestCount: number | null;
  backupType: string;
  databaseType: string;
  composeId: string | null;
  postgresId: string | null;
  mariadbId: string | null;
  mysqlId: string | null;
  mongoId: string | null;
  userId: string | null;
  metadata?: MongoRemoveMetadata$Outbound | string | null | undefined;
};

/** @internal */
export const MongoRemoveBackup$outboundSchema: z.ZodType<
  MongoRemoveBackup$Outbound,
  z.ZodTypeDef,
  MongoRemoveBackup
> = z.object({
  backupId: z.string(),
  appName: z.string(),
  schedule: z.string(),
  enabled: z.nullable(z.boolean()),
  database: z.string(),
  prefix: z.string(),
  serviceName: z.nullable(z.string()),
  destinationId: z.string(),
  keepLatestCount: z.nullable(z.number()),
  backupType: MongoRemoveBackupType$outboundSchema,
  databaseType: MongoRemoveDatabaseType$outboundSchema,
  composeId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  userId: z.nullable(z.string()),
  metadata: z.nullable(
    z.union([
      z.lazy(() => MongoRemoveMetadata$outboundSchema),
      MongoRemoveMetadataEnum$outboundSchema,
    ]),
  ).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveBackup$ {
  /** @deprecated use `MongoRemoveBackup$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveBackup$inboundSchema;
  /** @deprecated use `MongoRemoveBackup$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveBackup$outboundSchema;
  /** @deprecated use `MongoRemoveBackup$Outbound` instead. */
  export type Outbound = MongoRemoveBackup$Outbound;
}

export function mongoRemoveBackupToJSON(
  mongoRemoveBackup: MongoRemoveBackup,
): string {
  return JSON.stringify(
    MongoRemoveBackup$outboundSchema.parse(mongoRemoveBackup),
  );
}

export function mongoRemoveBackupFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveBackup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveBackup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveBackup' from JSON`,
  );
}

/** @internal */
export const MongoRemoveResponseBody$inboundSchema: z.ZodType<
  MongoRemoveResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  mongoId: z.string(),
  name: z.string(),
  appName: z.string(),
  description: z.nullable(z.string()),
  databaseUser: z.string(),
  databasePassword: z.string(),
  dockerImage: z.string(),
  command: z.nullable(z.string()),
  env: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  memoryLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  externalPort: z.nullable(z.number()),
  applicationStatus: MongoRemoveApplicationStatus$inboundSchema,
  healthCheckSwarm: z.nullable(
    z.lazy(() => MongoRemoveHealthCheckSwarm$inboundSchema),
  ),
  restartPolicySwarm: z.nullable(
    z.lazy(() => MongoRemoveRestartPolicySwarm$inboundSchema),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => MongoRemovePlacementSwarm$inboundSchema),
  ),
  updateConfigSwarm: z.nullable(
    z.lazy(() => MongoRemoveUpdateConfigSwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => MongoRemoveRollbackConfigSwarm$inboundSchema),
  ),
  modeSwarm: z.nullable(z.lazy(() => MongoRemoveModeSwarm$inboundSchema)),
  labelsSwarm: z.nullable(z.record(z.string())),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => MongoRemoveNetworkSwarm$inboundSchema)),
  ),
  replicas: z.number(),
  createdAt: z.string(),
  environmentId: z.string(),
  serverId: z.nullable(z.string()),
  replicaSets: z.nullable(z.boolean()),
  environment: z.lazy(() => MongoRemoveEnvironment$inboundSchema),
  mounts: z.array(z.lazy(() => MongoRemoveMount$inboundSchema)),
  server: z.nullable(z.lazy(() => MongoRemoveServer$inboundSchema)),
  backups: z.array(z.lazy(() => MongoRemoveBackup$inboundSchema)),
});

/** @internal */
export type MongoRemoveResponseBody$Outbound = {
  mongoId: string;
  name: string;
  appName: string;
  description: string | null;
  databaseUser: string;
  databasePassword: string;
  dockerImage: string;
  command: string | null;
  env: string | null;
  memoryReservation: string | null;
  memoryLimit: string | null;
  cpuReservation: string | null;
  cpuLimit: string | null;
  externalPort: number | null;
  applicationStatus: string;
  healthCheckSwarm: MongoRemoveHealthCheckSwarm$Outbound | null;
  restartPolicySwarm: MongoRemoveRestartPolicySwarm$Outbound | null;
  placementSwarm: MongoRemovePlacementSwarm$Outbound | null;
  updateConfigSwarm: MongoRemoveUpdateConfigSwarm$Outbound | null;
  rollbackConfigSwarm: MongoRemoveRollbackConfigSwarm$Outbound | null;
  modeSwarm: MongoRemoveModeSwarm$Outbound | null;
  labelsSwarm: { [k: string]: string } | null;
  networkSwarm: Array<MongoRemoveNetworkSwarm$Outbound> | null;
  replicas: number;
  createdAt: string;
  environmentId: string;
  serverId: string | null;
  replicaSets: boolean | null;
  environment: MongoRemoveEnvironment$Outbound;
  mounts: Array<MongoRemoveMount$Outbound>;
  server: MongoRemoveServer$Outbound | null;
  backups: Array<MongoRemoveBackup$Outbound>;
};

/** @internal */
export const MongoRemoveResponseBody$outboundSchema: z.ZodType<
  MongoRemoveResponseBody$Outbound,
  z.ZodTypeDef,
  MongoRemoveResponseBody
> = z.object({
  mongoId: z.string(),
  name: z.string(),
  appName: z.string(),
  description: z.nullable(z.string()),
  databaseUser: z.string(),
  databasePassword: z.string(),
  dockerImage: z.string(),
  command: z.nullable(z.string()),
  env: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  memoryLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  externalPort: z.nullable(z.number()),
  applicationStatus: MongoRemoveApplicationStatus$outboundSchema,
  healthCheckSwarm: z.nullable(
    z.lazy(() => MongoRemoveHealthCheckSwarm$outboundSchema),
  ),
  restartPolicySwarm: z.nullable(
    z.lazy(() => MongoRemoveRestartPolicySwarm$outboundSchema),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => MongoRemovePlacementSwarm$outboundSchema),
  ),
  updateConfigSwarm: z.nullable(
    z.lazy(() => MongoRemoveUpdateConfigSwarm$outboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => MongoRemoveRollbackConfigSwarm$outboundSchema),
  ),
  modeSwarm: z.nullable(z.lazy(() => MongoRemoveModeSwarm$outboundSchema)),
  labelsSwarm: z.nullable(z.record(z.string())),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => MongoRemoveNetworkSwarm$outboundSchema)),
  ),
  replicas: z.number(),
  createdAt: z.string(),
  environmentId: z.string(),
  serverId: z.nullable(z.string()),
  replicaSets: z.nullable(z.boolean()),
  environment: z.lazy(() => MongoRemoveEnvironment$outboundSchema),
  mounts: z.array(z.lazy(() => MongoRemoveMount$outboundSchema)),
  server: z.nullable(z.lazy(() => MongoRemoveServer$outboundSchema)),
  backups: z.array(z.lazy(() => MongoRemoveBackup$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveResponseBody$ {
  /** @deprecated use `MongoRemoveResponseBody$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveResponseBody$inboundSchema;
  /** @deprecated use `MongoRemoveResponseBody$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveResponseBody$outboundSchema;
  /** @deprecated use `MongoRemoveResponseBody$Outbound` instead. */
  export type Outbound = MongoRemoveResponseBody$Outbound;
}

export function mongoRemoveResponseBodyToJSON(
  mongoRemoveResponseBody: MongoRemoveResponseBody,
): string {
  return JSON.stringify(
    MongoRemoveResponseBody$outboundSchema.parse(mongoRemoveResponseBody),
  );
}

export function mongoRemoveResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveResponseBody' from JSON`,
  );
}

/** @internal */
export const MongoRemoveResponse$inboundSchema: z.ZodType<
  MongoRemoveResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoRemoveResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

/** @internal */
export type MongoRemoveResponse$Outbound =
  | MongoRemoveResponseBody$Outbound
  | models.ErrorT$Outbound;

/** @internal */
export const MongoRemoveResponse$outboundSchema: z.ZodType<
  MongoRemoveResponse$Outbound,
  z.ZodTypeDef,
  MongoRemoveResponse
> = z.union([
  z.lazy(() => MongoRemoveResponseBody$outboundSchema),
  models.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MongoRemoveResponse$ {
  /** @deprecated use `MongoRemoveResponse$inboundSchema` instead. */
  export const inboundSchema = MongoRemoveResponse$inboundSchema;
  /** @deprecated use `MongoRemoveResponse$outboundSchema` instead. */
  export const outboundSchema = MongoRemoveResponse$outboundSchema;
  /** @deprecated use `MongoRemoveResponse$Outbound` instead. */
  export type Outbound = MongoRemoveResponse$Outbound;
}

export function mongoRemoveResponseToJSON(
  mongoRemoveResponse: MongoRemoveResponse,
): string {
  return JSON.stringify(
    MongoRemoveResponse$outboundSchema.parse(mongoRemoveResponse),
  );
}

export function mongoRemoveResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveResponse' from JSON`,
  );
}
