/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SettingsReadMiddlewareTraefikConfigSecurity = {
  authorization: string;
};

/** @internal */
export const SettingsReadMiddlewareTraefikConfigSecurity$inboundSchema:
  z.ZodType<
    SettingsReadMiddlewareTraefikConfigSecurity,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Authorization: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "Authorization": "authorization",
    });
  });

/** @internal */
export type SettingsReadMiddlewareTraefikConfigSecurity$Outbound = {
  Authorization: string;
};

/** @internal */
export const SettingsReadMiddlewareTraefikConfigSecurity$outboundSchema:
  z.ZodType<
    SettingsReadMiddlewareTraefikConfigSecurity$Outbound,
    z.ZodTypeDef,
    SettingsReadMiddlewareTraefikConfigSecurity
  > = z.object({
    authorization: z.string(),
  }).transform((v) => {
    return remap$(v, {
      authorization: "Authorization",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SettingsReadMiddlewareTraefikConfigSecurity$ {
  /** @deprecated use `SettingsReadMiddlewareTraefikConfigSecurity$inboundSchema` instead. */
  export const inboundSchema =
    SettingsReadMiddlewareTraefikConfigSecurity$inboundSchema;
  /** @deprecated use `SettingsReadMiddlewareTraefikConfigSecurity$outboundSchema` instead. */
  export const outboundSchema =
    SettingsReadMiddlewareTraefikConfigSecurity$outboundSchema;
  /** @deprecated use `SettingsReadMiddlewareTraefikConfigSecurity$Outbound` instead. */
  export type Outbound = SettingsReadMiddlewareTraefikConfigSecurity$Outbound;
}

export function settingsReadMiddlewareTraefikConfigSecurityToJSON(
  settingsReadMiddlewareTraefikConfigSecurity:
    SettingsReadMiddlewareTraefikConfigSecurity,
): string {
  return JSON.stringify(
    SettingsReadMiddlewareTraefikConfigSecurity$outboundSchema.parse(
      settingsReadMiddlewareTraefikConfigSecurity,
    ),
  );
}

export function settingsReadMiddlewareTraefikConfigSecurityFromJSON(
  jsonString: string,
): SafeParseResult<
  SettingsReadMiddlewareTraefikConfigSecurity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SettingsReadMiddlewareTraefikConfigSecurity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SettingsReadMiddlewareTraefikConfigSecurity' from JSON`,
  );
}
