/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SettingsUpdateMiddlewareTraefikConfigRequest = {
  traefikConfig: string;
};

/** @internal */
export const SettingsUpdateMiddlewareTraefikConfigRequest$inboundSchema:
  z.ZodType<
    SettingsUpdateMiddlewareTraefikConfigRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    traefikConfig: z.string(),
  });

/** @internal */
export type SettingsUpdateMiddlewareTraefikConfigRequest$Outbound = {
  traefikConfig: string;
};

/** @internal */
export const SettingsUpdateMiddlewareTraefikConfigRequest$outboundSchema:
  z.ZodType<
    SettingsUpdateMiddlewareTraefikConfigRequest$Outbound,
    z.ZodTypeDef,
    SettingsUpdateMiddlewareTraefikConfigRequest
  > = z.object({
    traefikConfig: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SettingsUpdateMiddlewareTraefikConfigRequest$ {
  /** @deprecated use `SettingsUpdateMiddlewareTraefikConfigRequest$inboundSchema` instead. */
  export const inboundSchema =
    SettingsUpdateMiddlewareTraefikConfigRequest$inboundSchema;
  /** @deprecated use `SettingsUpdateMiddlewareTraefikConfigRequest$outboundSchema` instead. */
  export const outboundSchema =
    SettingsUpdateMiddlewareTraefikConfigRequest$outboundSchema;
  /** @deprecated use `SettingsUpdateMiddlewareTraefikConfigRequest$Outbound` instead. */
  export type Outbound = SettingsUpdateMiddlewareTraefikConfigRequest$Outbound;
}

export function settingsUpdateMiddlewareTraefikConfigRequestToJSON(
  settingsUpdateMiddlewareTraefikConfigRequest:
    SettingsUpdateMiddlewareTraefikConfigRequest,
): string {
  return JSON.stringify(
    SettingsUpdateMiddlewareTraefikConfigRequest$outboundSchema.parse(
      settingsUpdateMiddlewareTraefikConfigRequest,
    ),
  );
}

export function settingsUpdateMiddlewareTraefikConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  SettingsUpdateMiddlewareTraefikConfigRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SettingsUpdateMiddlewareTraefikConfigRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SettingsUpdateMiddlewareTraefikConfigRequest' from JSON`,
  );
}
