/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SshKeyAllSecurity = {
  authorization: string;
};

/** @internal */
export const SshKeyAllSecurity$inboundSchema: z.ZodType<
  SshKeyAllSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  Authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Authorization": "authorization",
  });
});

/** @internal */
export type SshKeyAllSecurity$Outbound = {
  Authorization: string;
};

/** @internal */
export const SshKeyAllSecurity$outboundSchema: z.ZodType<
  SshKeyAllSecurity$Outbound,
  z.ZodTypeDef,
  SshKeyAllSecurity
> = z.object({
  authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    authorization: "Authorization",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SshKeyAllSecurity$ {
  /** @deprecated use `SshKeyAllSecurity$inboundSchema` instead. */
  export const inboundSchema = SshKeyAllSecurity$inboundSchema;
  /** @deprecated use `SshKeyAllSecurity$outboundSchema` instead. */
  export const outboundSchema = SshKeyAllSecurity$outboundSchema;
  /** @deprecated use `SshKeyAllSecurity$Outbound` instead. */
  export type Outbound = SshKeyAllSecurity$Outbound;
}

export function sshKeyAllSecurityToJSON(
  sshKeyAllSecurity: SshKeyAllSecurity,
): string {
  return JSON.stringify(
    SshKeyAllSecurity$outboundSchema.parse(sshKeyAllSecurity),
  );
}

export function sshKeyAllSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SshKeyAllSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SshKeyAllSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SshKeyAllSecurity' from JSON`,
  );
}
