/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserGetMetricsTokenSecurity = {
  authorization: string;
};

/** @internal */
export const UserGetMetricsTokenSecurity$inboundSchema: z.ZodType<
  UserGetMetricsTokenSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  Authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Authorization": "authorization",
  });
});

/** @internal */
export type UserGetMetricsTokenSecurity$Outbound = {
  Authorization: string;
};

/** @internal */
export const UserGetMetricsTokenSecurity$outboundSchema: z.ZodType<
  UserGetMetricsTokenSecurity$Outbound,
  z.ZodTypeDef,
  UserGetMetricsTokenSecurity
> = z.object({
  authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    authorization: "Authorization",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserGetMetricsTokenSecurity$ {
  /** @deprecated use `UserGetMetricsTokenSecurity$inboundSchema` instead. */
  export const inboundSchema = UserGetMetricsTokenSecurity$inboundSchema;
  /** @deprecated use `UserGetMetricsTokenSecurity$outboundSchema` instead. */
  export const outboundSchema = UserGetMetricsTokenSecurity$outboundSchema;
  /** @deprecated use `UserGetMetricsTokenSecurity$Outbound` instead. */
  export type Outbound = UserGetMetricsTokenSecurity$Outbound;
}

export function userGetMetricsTokenSecurityToJSON(
  userGetMetricsTokenSecurity: UserGetMetricsTokenSecurity,
): string {
  return JSON.stringify(
    UserGetMetricsTokenSecurity$outboundSchema.parse(
      userGetMetricsTokenSecurity,
    ),
  );
}

export function userGetMetricsTokenSecurityFromJSON(
  jsonString: string,
): SafeParseResult<UserGetMetricsTokenSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGetMetricsTokenSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGetMetricsTokenSecurity' from JSON`,
  );
}
