/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserGetInvitationsSecurity = {
  authorization: string;
};

/** @internal */
export const UserGetInvitationsSecurity$inboundSchema: z.ZodType<
  UserGetInvitationsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  Authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Authorization": "authorization",
  });
});

/** @internal */
export type UserGetInvitationsSecurity$Outbound = {
  Authorization: string;
};

/** @internal */
export const UserGetInvitationsSecurity$outboundSchema: z.ZodType<
  UserGetInvitationsSecurity$Outbound,
  z.ZodTypeDef,
  UserGetInvitationsSecurity
> = z.object({
  authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    authorization: "Authorization",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserGetInvitationsSecurity$ {
  /** @deprecated use `UserGetInvitationsSecurity$inboundSchema` instead. */
  export const inboundSchema = UserGetInvitationsSecurity$inboundSchema;
  /** @deprecated use `UserGetInvitationsSecurity$outboundSchema` instead. */
  export const outboundSchema = UserGetInvitationsSecurity$outboundSchema;
  /** @deprecated use `UserGetInvitationsSecurity$Outbound` instead. */
  export type Outbound = UserGetInvitationsSecurity$Outbound;
}

export function userGetInvitationsSecurityToJSON(
  userGetInvitationsSecurity: UserGetInvitationsSecurity,
): string {
  return JSON.stringify(
    UserGetInvitationsSecurity$outboundSchema.parse(userGetInvitationsSecurity),
  );
}

export function userGetInvitationsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<UserGetInvitationsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGetInvitationsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGetInvitationsSecurity' from JSON`,
  );
}
