/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserGenerateTokenSecurity = {
  authorization: string;
};

/** @internal */
export const UserGenerateTokenSecurity$inboundSchema: z.ZodType<
  UserGenerateTokenSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  Authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Authorization": "authorization",
  });
});

/** @internal */
export type UserGenerateTokenSecurity$Outbound = {
  Authorization: string;
};

/** @internal */
export const UserGenerateTokenSecurity$outboundSchema: z.ZodType<
  UserGenerateTokenSecurity$Outbound,
  z.ZodTypeDef,
  UserGenerateTokenSecurity
> = z.object({
  authorization: z.string(),
}).transform((v) => {
  return remap$(v, {
    authorization: "Authorization",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserGenerateTokenSecurity$ {
  /** @deprecated use `UserGenerateTokenSecurity$inboundSchema` instead. */
  export const inboundSchema = UserGenerateTokenSecurity$inboundSchema;
  /** @deprecated use `UserGenerateTokenSecurity$outboundSchema` instead. */
  export const outboundSchema = UserGenerateTokenSecurity$outboundSchema;
  /** @deprecated use `UserGenerateTokenSecurity$Outbound` instead. */
  export type Outbound = UserGenerateTokenSecurity$Outbound;
}

export function userGenerateTokenSecurityToJSON(
  userGenerateTokenSecurity: UserGenerateTokenSecurity,
): string {
  return JSON.stringify(
    UserGenerateTokenSecurity$outboundSchema.parse(userGenerateTokenSecurity),
  );
}

export function userGenerateTokenSecurityFromJSON(
  jsonString: string,
): SafeParseResult<UserGenerateTokenSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGenerateTokenSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGenerateTokenSecurity' from JSON`,
  );
}
