/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VolumeBackupsDeleteRequest = {
  volumeBackupId: string;
};

/** @internal */
export const VolumeBackupsDeleteRequest$inboundSchema: z.ZodType<
  VolumeBackupsDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  volumeBackupId: z.string(),
});

/** @internal */
export type VolumeBackupsDeleteRequest$Outbound = {
  volumeBackupId: string;
};

/** @internal */
export const VolumeBackupsDeleteRequest$outboundSchema: z.ZodType<
  VolumeBackupsDeleteRequest$Outbound,
  z.ZodTypeDef,
  VolumeBackupsDeleteRequest
> = z.object({
  volumeBackupId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VolumeBackupsDeleteRequest$ {
  /** @deprecated use `VolumeBackupsDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = VolumeBackupsDeleteRequest$inboundSchema;
  /** @deprecated use `VolumeBackupsDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = VolumeBackupsDeleteRequest$outboundSchema;
  /** @deprecated use `VolumeBackupsDeleteRequest$Outbound` instead. */
  export type Outbound = VolumeBackupsDeleteRequest$Outbound;
}

export function volumeBackupsDeleteRequestToJSON(
  volumeBackupsDeleteRequest: VolumeBackupsDeleteRequest,
): string {
  return JSON.stringify(
    VolumeBackupsDeleteRequest$outboundSchema.parse(volumeBackupsDeleteRequest),
  );
}

export function volumeBackupsDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<VolumeBackupsDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VolumeBackupsDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VolumeBackupsDeleteRequest' from JSON`,
  );
}
